version: "3.1"

services:
  web:
    build: .
    restart: always
    ports:
    - "4000:4000"
    environment:
      MONGODB: mongodb://root:example@mongo:27017/
      PORT: 4000
      BBBSERVER: 
      BBBSECRET:
    links:
    - mongo
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example